# Import potřebných knihoven
import requests
from bs4 import BeautifulSoup
import csv
import re

# URL stránky s daty karet Pokémon TCG
url = "https://gamerant.com/pokemon-tcg-pocket-every-card-list-all-sets-full-complete-dex/"
headers = {
    "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 "
                  "(KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
} # must, bez toho to neslo
# Odeslání HTTP požadavku na stránku
response = requests.get(url, headers=headers)

# Vytvoření objektu BeautifulSoup pro parsování HTML
soup = BeautifulSoup(response.text, "html.parser")

# Seznam pro uložení všech karet (kód, název, závislosti)
all_cards = []

# Seznam pro uložení přeskočených řádků pro ladění
skipped_rows = []

# Definice evolučních řetězců pro Pokémony v TCG Pocket sadách
evolution_chains = {
    # Generation 1
    "Bulbasaur": {"stage": 1, "evolves_to": ["Ivysaur"]},
    "Ivysaur": {"stage": 2, "evolves_to": ["Venusaur", "Venusaur ex"], "requires": ["Bulbasaur"]},
    "Venusaur": {"stage": 3, "requires": ["Bulbasaur", "Ivysaur"]},
    "Venusaur ex": {"stage": 3, "requires": ["Bulbasaur", "Ivysaur"]},
    "Charmander": {"stage": 1, "evolves_to": ["Charmeleon"]},
    "Charmeleon": {"stage": 2, "evolves_to": ["Charizard", "Charizard ex"], "requires": ["Charmander"]},
    "Charizard": {"stage": 3, "requires": ["Charmander", "Charmeleon"]},
    "Charizard ex": {"stage": 3, "requires": ["Charmander", "Charmeleon"]},
    "Squirtle": {"stage": 1, "evolves_to": ["Wartortle"]},
    "Wartortle": {"stage": 2, "evolves_to": ["Blastoise", "Blastoise ex"], "requires": ["Squirtle"]},
    "Blastoise": {"stage": 3, "requires": ["Squirtle", "Wartortle"]},
    "Blastoise ex": {"stage": 3, "requires": ["Squirtle", "Wartortle"]},
    "Caterpie": {"stage": 1, "evolves_to": ["Metapod"]},
    "Metapod": {"stage": 2, "evolves_to": ["Butterfree"], "requires": ["Caterpie"]},
    "Butterfree": {"stage": 3, "requires": ["Caterpie", "Metapod"]},
    "Weedle": {"stage": 1, "evolves_to": ["Kakuna"]},
    "Kakuna": {"stage": 2, "evolves_to": ["Beedrill", "Beedrill ex"], "requires": ["Weedle"]},
    "Beedrill": {"stage": 3, "requires": ["Weedle", "Kakuna"]},
    "Beedrill ex": {"stage": 3, "requires": ["Weedle", "Kakuna"]},
    "Pidgey": {"stage": 1, "evolves_to": ["Pidgeotto"]},
    "Pidgeotto": {"stage": 2, "requires": ["Pidgey"], "evolves_to": ["Pidgeot", "Pidgeot ex"]},
    "Pidgeot": {"stage": 3, "requires": ["Pidgey", "Pidgeotto"]},
    "Pidgeot ex": {"stage": 3, "requires": ["Pidgey", "Pidgeotto"]},
    "Rattata": {"stage": 1, "evolves_to": ["Raticate"]},
    "Raticate": {"stage": 2, "requires": ["Rattata"]},
    "Spearow": {"stage": 1, "evolves_to": ["Fearow"]},
    "Fearow": {"stage": 2, "requires": ["Spearow"]},
    "Ekans": {"stage": 1, "evolves_to": ["Arbok"]},
    "Arbok": {"stage": 2, "requires": ["Ekans"]},
    "Pikachu": {"stage": 1, "evolves_to": ["Raichu", "Raichu ex"]},
    "Pikachu ex": {"stage": 1, "evolves_to": ["Raichu", "Raichu ex"]},
    "Raichu": {"stage": 2, "requires": ["Pikachu", "Pikachu ex"]},
    "Raichu ex": {"stage": 2, "requires": ["Pikachu", "Pikachu ex"]},
    "Sandshrew": {"stage": 1, "evolves_to": ["Sandslash"]},
    "Sandslash": {"stage": 2, "requires": ["Sandshrew"]},
    "Nidoran ♀": {"stage": 1, "evolves_to": ["Nidorina"]},
    "Nidorina": {"stage": 2, "requires": ["Nidoran ♀"], "evolves_to": ["Nidoqueen"]},
    "Nidoqueen": {"stage": 3, "requires": ["Nidoran ♀", "Nidorina"]},
    "Nidoran ♂": {"stage": 1, "evolves_to": ["Nidorino"]},
    "Nidorino": {"stage": 2, "requires": ["Nidoran ♂"], "evolves_to": ["Nidoking"]},
    "Nidoking": {"stage": 3, "requires": ["Nidoran ♂", "Nidorino"]},
    "Clefairy": {"stage": 1, "evolves_to": ["Clefable"]},
    "Clefable": {"stage": 2, "requires": ["Clefairy"]},
    "Vulpix": {"stage": 1, "evolves_to": ["Ninetales"]},
    "Ninetales": {"stage": 2, "requires": ["Vulpix"]},
    "Jigglypuff": {"stage": 1, "evolves_to": ["Wigglytuff", "Wigglytuff ex"]},
    "Wigglytuff": {"stage": 2, "requires": ["Jigglypuff"]},
    "Wigglytuff ex": {"stage": 2, "requires": ["Jigglypuff"]},
    "Zubat": {"stage": 1, "evolves_to": ["Golbat"]},
    "Golbat": {"stage": 2, "evolves_to": ["Crobat"], "requires": ["Zubat"]},
    "Oddish": {"stage": 1, "evolves_to": ["Gloom"]},
    "Gloom": {"stage": 2, "requires": ["Oddish"], "evolves_to": ["Vileplume", "Bellossom"]},
    "Vileplume": {"stage": 3, "requires": ["Oddish", "Gloom"]},
    "Paras": {"stage": 1, "evolves_to": ["Parasect"]},
    "Parasect": {"stage": 2, "requires": ["Paras"]},
    "Venonat": {"stage": 1, "evolves_to": ["Venomoth"]},
    "Venomoth": {"stage": 2, "requires": ["Venonat"]},
    "Diglett": {"stage": 1, "evolves_to": ["Dugtrio"]},
    "Dugtrio": {"stage": 2, "requires": ["Diglett"]},
    "Meowth": {"stage": 1, "evolves_to": ["Persian"]},
    "Persian": {"stage": 2, "requires": ["Meowth"]},
    "Psyduck": {"stage": 1, "evolves_to": ["Golduck"]},
    "Golduck": {"stage": 2, "requires": ["Psyduck"]},
    "Mankey": {"stage": 1, "evolves_to": ["Primeape"]},
    "Primeape": {"stage": 2, "requires": ["Mankey"]},
    "Growlithe": {"stage": 1, "evolves_to": ["Arcanine", "Arcanine ex"]},
    "Arcanine": {"stage": 2, "requires": ["Growlithe"]},
    "Arcanine ex": {"stage": 2, "requires": ["Growlithe"]},
    "Poliwag": {"stage": 1, "evolves_to": ["Poliwhirl"]},
    "Poliwhirl": {"stage": 2, "requires": ["Poliwag"], "evolves_to": ["Poliwrath"]},
    "Poliwrath": {"stage": 3, "requires": ["Poliwag", "Poliwhirl"]},
    "Abra": {"stage": 1, "evolves_to": ["Kadabra"]},
    "Kadabra": {"stage": 2, "requires": ["Abra"], "evolves_to": ["Alakazam"]},
    "Alakazam": {"stage": 3, "requires": ["Abra", "Kadabra"]},
    "Machop": {"stage": 1, "evolves_to": ["Machoke"]},
    "Machoke": {"stage": 2, "requires": ["Machop"], "evolves_to": ["Machamp", "Machamp ex"]},
    "Machamp": {"stage": 3, "requires": ["Machop", "Machoke"]},
    "Machamp ex": {"stage": 3, "requires": ["Machop", "Machoke"]},
    "Bellsprout": {"stage": 1, "evolves_to": ["Weepinbell"]} ,
    "Weepinbell": {"stage": 2, "requires": ["Bellsprout"], "evolves_to": ["Victreebel"]},
    "Victreebel": {"stage": 3, "requires": ["Bellsprout", "Weepinbell"]},
    "Tentacool": {"stage": 1, "evolves_to": ["Tentacruel"]},
    "Tentacruel": {"stage": 2, "requires": ["Tentacool"]},
    "Geodude": {"stage": 1, "evolves_to": ["Graveler"]},
    "Graveler": {"stage": 2, "requires": ["Geodude"], "evolves_to": ["Golem"]},
    "Golem": {"stage": 3, "requires": ["Geodude", "Graveler"]},
    "Ponyta": {"stage": 1, "evolves_to": ["Rapidash"]},
    "Rapidash": {"stage": 2, "requires": ["Ponyta"]},
    "Slowpoke": {"stage": 1, "evolves_to": ["Slowbro"]},
    "Slowbro": {"stage": 2, "requires": ["Slowpoke"]},
    "Doduo": {"stage": 1, "evolves_to": ["Dodrio"]},
    "Dodrio": {"stage": 2, "requires": ["Doduo"]},
    "Seel": {"stage": 1, "evolves_to": ["Dewgong"]},
    "Dewgong": {"stage": 2, "requires": ["Seel"]},
    "Grimer": {"stage": 1, "evolves_to": ["Muk"]},
    "Muk": {"stage": 2, "requires": ["Grimer"]},
    "Gastly": {"stage": 1, "evolves_to": ["Haunter"]},
    "Haunter": {"stage": 2, "requires": ["Gastly"], "evolves_to": ["Gengar", "Gengar ex"]},
    "Gengar": {"stage": 3, "requires": ["Gastly", "Haunter"]},
    "Gengar ex": {"stage": 3, "requires": ["Gastly", "Haunter"]},
    "Drowzee": {"stage": 1, "evolves_to": ["Hypno"]},
    "Hypno": {"stage": 2, "requires": ["Drowzee"]},
    "Krabby": {"stage": 1, "evolves_to": ["Kingler"]},
    "Kingler": {"stage": 2, "requires": ["Krabby"]} ,
    "Voltorb": {"stage": 1, "evolves_to": ["Electrode"]},
    "Electrode": {"stage": 2, "requires": ["Voltorb"]} ,
    "Exeggcute": {"stage": 1, "evolves_to": ["Exeggutor", "Exeggutor ex", "Alolan Exeggutor"]},
    "Exeggutor": {"stage": 2, "requires": ["Exeggcute"]},
    "Exeggutor ex": {"stage": 2, "requires": ["Exeggcute"]},
    "Alolan Exeggutor": {"stage": 2, "requires": ["Exeggcute"]},
    "Cubone": {"stage": 1, "evolves_to": ["Marowak", "Marowak ex", "Alolan Marowak"]},
    "Marowak": {"stage": 2, "requires": ["Cubone"]},
    "Marowak ex": {"stage": 2, "requires": ["Cubone"]},
    "Alolan Marowak": {"stage": 2, "requires": ["Cubone"]},
    "Koffing": {"stage": 1, "evolves_to": ["Weezing"]},
    "Weezing": {"stage": 2, "requires": ["Koffing"]},
    # "Rhyhorn": {"stage": 1, "evolves_to": ["Rhydon"]},
    # "Rhydon": {"stage": 2, "requires": ["Rhyhorn"]},
    "Horsea": {"stage": 1, "evolves_to": ["Seadra"]},
    "Seadra": {"stage": 2, "requires": ["Horsea"]},
    "Goldeen": {"stage": 1, "evolves_to": ["Seaking"]},
    "Seaking": {"stage": 2, "requires": ["Goldeen"]},
    "Staryu": {"stage": 1, "evolves_to": ["Starmie", "Starmie ex"]},
    "Starmie": {"stage": 2, "requires": ["Staryu"]},
    "Starmie ex": {"stage": 2, "requires": ["Staryu"]},
    "Magikarp": {"stage": 1, "evolves_to": ["Gyarados", "Gyarados ex"]},
    "Gyarados": {"stage": 2, "requires": ["Magikarp"]},
    "Gyarados ex": {"stage": 2, "requires": ["Magikarp"]},
    "Eevee": {"stage": 1, "evolves_to": ["Glaceon", "Sylveon", "Leafeon", "Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Glaceon ex", "Sylveon ex", "Leafeon ex", "Vaporeon ex", "Jolteon ex", "Flareon ex", "Espeon ex", "Umbreon ex"]},
    "Eevee ex": {"stage": 1, "evolves_to": ["Glaceon", "Sylveon", "Leafeon", "Vaporeon", "Jolteon", "Flareon", "Espeon", "Umbreon", "Glaceon ex", "Sylveon ex", "Leafeon ex", "Vaporeon ex", "Jolteon ex", "Flareon ex", "Espeon ex", "Umbreon ex"]},
    "Vaporeon": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Vaporeon ex": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Jolteon": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Jolteon ex": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},   
    "Flareon": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Flareon ex": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},  
    "Espeon": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Espeon ex": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Umbreon": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Umbreon ex": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Glaceon": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Glaceon ex": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Sylveon": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Sylveon ex": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Leafeon": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Leafeon ex": {"stage": 2, "requires": ["Eevee", "Eevee ex"]},
    "Kabuto": {"stage": 1, "evolves_to": ["Kabutops"]},
    "Kabutops": {"stage": 2, "requires": ["Kabuto"]},
    "Omanyte": {"stage": 1, "evolves_to": ["Omastar"]},
    "Omastar": {"stage": 2, "requires": ["Omanyte"]},
    "Dratini": {"stage": 1, "evolves_to": ["Dragonair"]},
    "Dragonair": {"stage": 2, "evolves_to": ["Dragonite"], "requires": ["Dratini"]},
    "Dragonite": {"stage": 3, "requires": ["Dratini", "Dragonair"]},
    "Old Amber": {"stage": 1, "evolves_to": ["Aerodactyl", "Aerodactyl ex"]},
    "Aerodactyl": {"stage": 2, "requires": ["Old Amber"]},
    "Aerodactyl ex": {"stage": 2, "requires": ["Old Amber"]},

    # A1
    "Cottonee": {"stage": 1, "evolves_to": ["Whimsicott"]},
    "Whimsicott": {"stage": 2, "requires": ["Cottonee"]},
    "Petilil": {"stage": 1, "evolves_to": ["Lilligant"]},
    "Lilligant": {"stage": 2, "requires": ["Petilil"]},
    "Skiddo": {"stage": 1, "evolves_to": ["Gogoat"]},
    "Gogoat": {"stage": 2, "requires": ["Skiddo"]},
    "Salandit": {"stage": 1, "evolves_to": ["Salazzle"]},
    "Salazzle": {"stage": 2, "requires": ["Salandit"]},
    "Sizzlipede": {"stage": 1, "evolves_to": ["Centiskorch"]},
    "Centiskorch": {"stage": 2, "requires": ["Sizzlipede"]},
    "Ducklett": {"stage": 1, "evolves_to": ["Swanna"]},
    "Swanna": {"stage": 2, "requires": ["Ducklett"]},
    "Froakie": {"stage": 1, "evolves_to": ["Frogadier"]},
    "Frogadier": {"stage": 2, "requires": ["Froakie"], "evolves_to": ["Greninja"]},
    "Greninja": {"stage": 3, "requires": ["Froakie", "Frogadier"]},
    "Snom": {"stage": 1, "evolves_to": ["Frosmoth"]},
    "Frosmoth": {"stage": 2, "requires": ["Snom"]},
    "Blitzle": {"stage": 1, "evolves_to": ["Zebstrika"]},
    "Zebstrika": {"stage": 2, "requires": ["Blitzle"]},
    "Tynamo": {"stage": 1, "evolves_to": ["Eelektrik"]},
    "Eelektrik": {"stage": 2, "requires": ["Tynamo"], "evolves_to": ["Eelektross"]},
    "Eelektross": {"stage": 3, "requires": ["Tynamo", "Eelektrik"]},
    "Helioptile": {"stage": 1, "evolves_to": ["Heliolisk"]},
    "Heliolisk": {"stage": 2, "requires": ["Helioptile"]},
    "Ralts": {"stage": 1, "evolves_to": ["Kirlia"]},
    "Kirlia": {"stage": 2, "requires": ["Ralts"], "evolves_to": ["Gardevoir", "Gardevoir ex", "Gallede", "Gallede ex"]},
    "Gardevoir": {"stage": 3, "requires": ["Ralts", "Kirlia"]},
    "Gardevoir ex": {"stage": 3, "requires": ["Ralts", "Kirlia"]},
    "Gallade": {"stage": 3, "requires": ["Ralts", "Kirlia"]},
    "Gallade ex": {"stage": 3, "requires": ["Ralts", "Kirlia"]},
    "Woobat": {"stage": 1, "evolves_to": ["Swoobat"]},
    "Swoobat": {"stage": 2, "requires": ["Woobat"]},
    "Golett": {"stage": 1, "evolves_to": ["Golurk"]},
    "Golurk": {"stage": 2, "requires": ["Golett"]},
    "Mienfoo": {"stage": 1, "evolves_to": ["Mienshao"]},
    "Mienshao": {"stage": 2, "requires": ["Mienfoo"]},
    "Clobbopus": {"stage": 1, "evolves_to": ["Grapploct"]},
    "Grapploct": {"stage": 2, "requires": ["Clobbopus"]},
    "Pawniard": {"stage": 1, "evolves_to": ["Bisharp"]},
    "Bisharp": {"stage": 2, "requires": ["Pawniard"]},
    "Meltan": {"stage": 1, "evolves_to": ["Melmetal"]},
    "Melmetal": {"stage": 2, "requires": ["Meltan"]},
    "Minccino": {"stage": 1, "evolves_to": ["Cinccino"]},
    "Cinccino": {"stage": 2, "requires": ["Minccino"]},
    "Wooloo": {"stage": 1, "evolves_to": ["Dubwool"]},
    "Dubwool": {"stage": 2, "requires": ["Wooloo"]},
    #A1a
    "Snivy": {"stage": 1, "evolves_to": ["Servine"]},
    "Servine": {"stage": 2, "requires": ["Snivy"], "evolves_to": ["Serperior"]},
    "Morelull": {"stage": 1, "evolves_to": ["Shiinotic"]},
    "Shiinotic": {"stage": 2, "requires": ["Morelull"]},
    "Larvesta": {"stage": 1, "evolves_to": ["Volcarona"]},
    "Volcarona": {"stage": 2, "requires": ["Larvesta"]},
    "Finneon": {"stage": 1, "evolves_to": ["Lumineon"]},
    "Lumineon": {"stage": 2, "requires": ["Finneon"]},
    "Chewtie": {"stage": 1, "evolves_to": ["Drednaw"]},
    "Drednaw": {"stage": 2, "requires": ["Chewtie"]},
    "Elgyem": {"stage": 1, "evolves_to": ["Beheeyem"]},
    "Beheeyem": {"stage": 2, "requires": ["Elgyem"]},
    "Flabébé": {"stage": 1, "evolves_to": ["Floette"]},
    "Floette": {"stage": 2, "requires": ["Flabébé"], "evolves_to": ["Florges"]},
    "Florges": {"stage": 3, "requires": ["Flabébé", "Floette"]},
    "Swirlix": {"stage": 1, "evolves_to": ["Slurpuff"]},
    "Slurpuff": {"stage": 2, "requires": ["Swirlix"]},
    "Purrloin": {"stage": 1, "evolves_to": ["Liepard"]},
    "Liepard": {"stage": 2, "requires": ["Purrloin"]},
    "Venipede": {"stage": 1, "evolves_to": ["Whirlipede"]},
    "Whirlipede": {"stage": 2, "requires": ["Venipede"], "evolves_to": ["Scolipede"]},
    "Scolipede": {"stage": 3, "requires": ["Venipede", "Whirlipede"]},
    # A2
    "Combee": {"stage": 1, "evolves_to": ["Vespiquen"]},
    "Vespiquen": {"stage": 2, "requires": ["Combee"]},
    "Bellossom": {"stage": 3, "requires": ["Oddish", "Gloom"]},
    "Tangela": {"stage": 1, "evolves_to": ["Tangrowth"]},
    "Tangrowth": {"stage": 2, "requires": ["Tangela"]},
    "Yanma": {"stage": 1, "evolves_to": ["Yanmega", "Yanmega ex"]},
    "Yanmega": {"stage": 2, "requires": ["Yanma"]},
    "Yanmega ex": {"stage": 2, "requires": ["Yanma"]},
    "Roselia": {"stage": 1, "evolves_to": ["Roserade"]},
    "Roserade": {"stage": 2, "requires": ["Roselia"]},
    "Turtwig": {"stage": 1, "evolves_to": ["Grotle"]},
    "Grotle": {"stage": 2, "requires": ["Turtwig"], "evolves_to": ["Torterra"]},
    "Kricketot": {"stage": 1, "evolves_to": ["Kricketune"]},
    "Kricketune": {"stage": 2, "requires": ["Kricketot"]},
    "Burmy": {"stage": 1, "evolves_to": ["Wormadam", "Mothim"]},
    "Wormadam": {"stage": 2, "requires": ["Burmy"]},
    "Mothim": {"stage": 2, "requires": ["Burmy"]},
    "Combee": {"stage": 1, "evolves_to": ["Vespiquen"]},
    "Vespiquen": {"stage": 2, "requires": ["Combee"]},
    "Magmar": {"stage": 1, "evolves_to": ["Magmortar"]},
    "Magmortar": {"stage": 2, "requires": ["Magmar"]},
    "Slugma": {"stage": 1, "evolves_to": ["Magcargo"]},
    "Magcargo": {"stage": 2, "requires": ["Slugma"]},
    "Chimchar": {"stage": 1, "evolves_to": ["Monferno"]},
    "Monferno": {"stage": 2, "requires": ["Chimchar"], "evolves_to": ["Infernape", "Infernape ex"]},
    "Infernape": {"stage": 3, "requires": ["Chimchar", "Monferno"]},
    "Infernape ex": {"stage": 3, "requires": ["Chimchar", "Monferno"]},
    "Swinub": {"stage": 1, "evolves_to": ["Piloswine"]},
    "Piloswine": {"stage": 2, "requires": ["Swinub"], "evolves_to": ["Mamoswine"]},
    "Mamoswine": {"stage": 3, "requires": ["Swinub", "Piloswine"]}, 
    "Piplup": {"stage": 1, "evolves_to": ["Prinplup"]},
    "Prinplup": {"stage": 2, "requires": ["Piplup"], "evolves_to": ["Empoleon"]},
    "Empoleon": {"stage": 3, "requires": ["Piplup", "Prinplup"]},
    "Buizel": {"stage": 1, "evolves_to": ["Floatzel"]},
    "Floatzel": {"stage": 2, "requires": ["Buizel"]},
    "Shellos": {"stage": 1, "evolves_to": ["Gastrodon"]},
    "Gastrodon": {"stage": 2, "requires": ["Shellos"]},
    "Snover": {"stage": 1, "evolves_to": ["Abomasnow"]},
    "Abomasnow": {"stage": 2, "requires": ["Snover"]},
    "Magnemite": {"stage": 1, "evolves_to": ["Magneton"]},
    "Magneton": {"stage": 2, "requires": ["Magnemite"], "evolves_to": ["Magnezone"]},
    "Magnezone": {"stage": 3, "requires": ["Magnemite", "Magneton"]},
    "Electabuzz": {"stage": 1, "evolves_to": ["Electivire"]},
    "Electivire": {"stage": 2, "requires": ["Electabuzz"]},
    "Shinx": {"stage": 1, "evolves_to": ["Luxio"]},
    "Luxio": {"stage": 2, "requires": ["Shinx"], "evolves_to": ["Luxray"]},
    "Luxray": {"stage": 3, "requires": ["Shinx", "Luxio"]},
    "Togepi": {"stage": 1, "evolves_to": ["Togetic"]},
    "Togetic": {"stage": 2, "requires": ["Togepi"], "evolves_to": ["Togekiss"]},
    "Togekiss": {"stage": 3, "requires": ["Togepi", "Togetic"]},
    "Misdreavus": {"stage": 1, "evolves_to": ["Mismagius", "Mismagius ex"]},
    "Mismagius": {"stage": 2, "requires": ["Misdreavus"]},
    "Mismagius ex": {"stage": 2, "requires": ["Misdreavus"]},
    "Duskull": {"stage": 1, "evolves_to": ["Dusclops"]},
    "Dusclops": {"stage": 2, "requires": ["Duskull"], "evolves_to": ["Dusknoir"]},
    "Dusknoir": {"stage": 3, "requires": ["Duskull", "Dusclops"]},
    "Drifloon": {"stage": 1, "evolves_to": ["Drifblim"]},
    "Drifblim": {"stage": 2, "requires": ["Drifloon"]},
    "Rhyhorn": {"stage": 1, "evolves_to": ["Rhydon"]},
    "Rhydon": {"stage": 2, "requires": ["Rhyhorn"], "evolves_to": ["Rhyperior"]},
    "Rhyperior": {"stage": 3, "requires": ["Rhyhorn", "Rhydon"]},
    "Gligar": {"stage": 1, "evolves_to": ["Gliscor"]},
    "Gliscor": {"stage": 2, "requires": ["Gligar"]},
    "Unidentified Fossil": {"stage": 1, "evolves_to": ["Cranidos"]},
    "Cranidos": {"stage": 2, "requires": ["Unidentified Fossil"], "evolves_to": ["Rampardos"]},
    "Rampardos": {"stage": 3, "requires": ["Unidentified Fossil", "Cranidos"]},
    "Riolu": {"stage": 1, "evolves_to": ["Lucario", "Lucario ex"]},
    "Lucario": {"stage": 2, "requires": ["Riolu"]},
    "Lucario ex": {"stage": 2, "requires": ["Riolu"]},
    "Hippopotas": {"stage": 1, "evolves_to": ["Hippowdon"]},
    "Hippowdon": {"stage": 2, "requires": ["Hippopotas"]},
    "Murkrow": {"stage": 1, "evolves_to": ["Honchkrow"]},
    "Honchkrow": {"stage": 2, "requires": ["Murkrow"]},
    "Sneasel": {"stage": 1, "evolves_to": ["Weavile", "Weavile ex"]},
    "Weavile": {"stage": 2, "requires": ["Sneasel"]},
    "Weavile ex": {"stage": 2, "requires": ["Sneasel"]},
    "Poochyena": {"stage": 1, "evolves_to": ["Mightyena"]},
    "Mightyena": {"stage": 2, "requires": ["Poochyena"]},
    "Stunky": {"stage": 1, "evolves_to": ["Skuntank"]},
    "Skuntank": {"stage": 2, "requires": ["Stunky"]},
    "Skorupi": {"stage": 1, "evolves_to": ["Drapion"]},
    "Drapion": {"stage": 2, "requires": ["Skorupi"]},
    "Croagunk": {"stage": 1, "evolves_to": ["Toxicroak"]},
    "Toxicroak": {"stage": 2, "requires": ["Croagunk"]},
    "Armor Fossil": {"stage": 1, "evolves_to": ["Shieldon"]},
    "Shieldon": {"stage": 2, "requires": ["Armor Fossil"], "evolves_to": ["Bastiodon"]},
    "Bastiodon": {"stage": 3, "requires": ["Armor Fossil", "Shieldon"]},
    "Bronzor": {"stage": 1, "evolves_to": ["Bronzong"]},
    "Bronzong": {"stage": 2, "requires": ["Bronzor"]},
    "Gible": {"stage": 1, "evolves_to": ["Gabite"]},
    "Gabite": {"stage": 2, "requires": ["Gible"], "evolves_to": ["Garchomp"]},
    "Garchomp": {"stage": 3, "requires": ["Gible", "Gabite"]},
    "Lickitung": {"stage": 1, "evolves_to": ["Lickilicky", "Lickilicky ex"]},
    "Lickilicky": {"stage": 2, "requires": ["Lickitung"]},
    "Lickilicky ex": {"stage": 2, "requires": ["Lickitung"]},
    "Porygon": {"stage": 1, "evolves_to": ["Porygon 2"]},
    "Porygon 2": {"stage": 2, "requires": ["Porygon"], "evolves_to": ["Porygon-Z"]},
    "Porygon-Z": {"stage": 3, "requires": ["Porygon", "Porygon 2"]},
    "Aipom": {"stage": 1, "evolves_to": ["Ambipom"]},
    "Ambipom": {"stage": 2, "requires": ["Aipom"]},
    "Starly": {"stage": 1, "evolves_to": ["Staravia"]},
    "Staravia": {"stage": 2, "requires": ["Starly"], "evolves_to": ["Staraptor"]},
    "Staraptor": {"stage": 3, "requires": ["Starly", "Staravia"]},
    "Bidoof": {"stage": 1, "evolves_to": ["Bibarel", "Bibarel ex"]},
    "Bibarel": {"stage": 2, "requires": ["Bidoof"]},
    "Bibarel ex": {"stage": 2, "requires": ["Bidoof"]},
    "Buneary": {"stage": 1, "evolves_to": ["Lopunny"]},
    "Lopunny": {"stage": 2, "requires": ["Buneary"]},
    "Glameow": {"stage": 1, "evolves_to": ["Purugly"]},
    "Purugly": {"stage": 2, "requires": ["Glameow"]},
    # A2a
    "Cherubi": {"stage": 1, "evolves_to": ["Cherrim"]},
    "Cherrim": {"stage": 2, "requires": ["Cherubi"]},
    "Houndour": {"stage": 1, "evolves_to": ["Houndoom"]},
    "Houndoom": {"stage": 2, "requires": ["Houndour"]},
    "Marill": {"stage": 1, "evolves_to": ["Azumarill"]},
    "Azumarill": {"stage": 2, "requires": ["Marill"]},
    "Barboach": {"stage": 1, "evolves_to": ["Whiscash"]},
    "Whiscash": {"stage": 2, "requires": ["Barboach"]},
    "Electrike": {"stage": 1, "evolves_to": ["Manectric"]},
    "Manectric": {"stage": 2, "requires": ["Electrike"]},
    "Phanpy": {"stage": 1, "evolves_to": ["Donphan"]},
    "Donphan": {"stage": 2, "requires": ["Phanpy"]},
    "Larvitar": {"stage": 1, "evolves_to": ["Pupitar"]},
    "Pupitar": {"stage": 2, "requires": ["Larvitar"], "evolves_to": ["Tyranitar"]},
    "Tyranitar": {"stage": 3, "requires": ["Larvitar", "Pupitar"]},
    "Meditite": {"stage": 1, "evolves_to": ["Medicham"]},
    "Medicham": {"stage": 2, "requires": ["Meditite"]},
    "Gible": {"stage": 1, "evolves_to": ["Gabite"]},
    "Gabite": {"stage": 2, "requires": ["Gible"], "evolves_to": ["Garchomp", "Garchomp ex"]},
    "Garchomp": {"stage": 3, "requires": ["Gible", "Gabite"]},
    "Garchomp ex": {"stage": 3, "requires": ["Gible", "Gabite"]},
    "Nosepass": {"stage": 1, "evolves_to": ["Probopass", "Probopass ex"]},
    "Probopass": {"stage": 2, "requires": ["Nosepass"]},
    "Probopass ex": {"stage": 2, "requires": ["Nosepass"]},
    "Hoothoot": {"stage": 1, "evolves_to": ["Noctowl"]},
    "Noctowl": {"stage": 2, "requires": ["Hoothoot"]},
    #A2b
    "Sprigatito": {"stage": 1, "evolves_to": ["Floragato"]},
    "Floragato": {"stage": 2, "requires": ["Sprigatito"], "evolves_to": ["Meowscarada"]},
    "Meowscarada": {"stage": 3, "requires": ["Sprigatito", "Floragato"]},
    "Wiglett": {"stage": 1, "evolves_to": ["Wugtrio", "Wugtrio ex"]},
    "Wugtrio": {"stage": 2, "requires": ["Wiglett"]},
    "Wugtrio ex": {"stage": 2, "requires": ["Wiglett"]},
    "Pawmi": {"stage": 1, "evolves_to": ["Pawmo"]},
    "Pawmo": {"stage": 2, "requires": ["Pawmi"], "evolves_to": ["Pawmot"]},
    "Pawmot": {"stage": 3, "requires": ["Pawmi", "Pawmo"]},
    "Paldean Wooper": {"stage": 1, "evolves_to": ["Paldean Clodsire ex"]},
    "Paldean Clodsire ex": {"stage": 2, "requires": ["Paldean Wooper"]},
    "Shroodle": {"stage": 1, "evolves_to": ["Grafaiai"]},
    "Grafaiai": {"stage": 2, "requires": ["Shroodle"]},
    "Tinkatink": {"stage": 1, "evolves_to": ["Tinkatuff"]},
    "Tinkatuff": {"stage": 2, "requires": ["Tinkatink"], "evolves_to": ["Tinkaton", "Tinkaton ex"]},
    "Tinkaton": {"stage": 3, "requires": ["Tinkatink", "Tinkatuff"]},
    "Tinkaton ex": {"stage": 3, "requires": ["Tinkatink", "Tinkatuff"]},
    "Varoom": {"stage": 1, "evolves_to": ["Revavroom"]},
    "Revavroom": {"stage": 2, "requires": ["Varoom"]},
    "Gimmighoul": {"stage": 1, "evolves_to": ["Gholdengo"]},
    "Gholdengo": {"stage": 2, "requires": ["Gimmighoul"]},
    #A3
    "Surskit": {"stage": 1, "evolves_to": ["Masquerain"]},
    "Masquerain": {"stage": 2, "requires": ["Surskit"]},
    "Phantump": {"stage": 1, "evolves_to": ["Trevenant"]},
    "Trevenant": {"stage": 2, "requires": ["Phantump"]},
    "Rowlet": {"stage": 1, "evolves_to": ["Dartrix"]},
    "Dartrix": {"stage": 2, "requires": ["Rowlet"], "evolves_to": ["Decidueye", "Decidueye ex"]},
    "Decidueye": {"stage": 3, "requires": ["Rowlet", "Dartrix"]},
    "Decidueye ex": {"stage": 3, "requires": ["Rowlet", "Dartrix"]},
    "Fomantis": {"stage": 1, "evolves_to": ["Lurantis"]},
    "Lurantis": {"stage": 2, "requires": ["Fomantis"]},
    "Bounsweet": {"stage": 1, "evolves_to": ["Steenee"]},
    "Steenee": {"stage": 2, "requires": ["Bounsweet"], "evolves_to": ["Tsareena"]},
    "Tsareena": {"stage": 3, "requires": ["Bounsweet", "Steenee"]},
    "Wimpod": {"stage": 1, "evolves_to": ["Golisopod"]},
    "Golisopod": {"stage": 2, "requires": ["Wimpod"]},
    "Fletchinder": {"stage": 1, "evolves_to": ["Talonflame"]},
    "Talonflame": {"stage": 2, "requires": ["Fletchinder"]},
    "Litten": {"stage": 1, "evolves_to": ["Torracat"]},
    "Torracat": {"stage": 2, "requires": ["Litten"], "evolves_to": ["Incineroar", "Incineroar ex"]},
    "Incineroar": {"stage": 3, "requires": ["Litten", "Torracat"]},
    "Incineroar ex": {"stage": 3, "requires": ["Litten", "Torracat"]},
    "Alolan Sandshrew": {"stage": 1, "evolves_to": ["Alolan Sandslash"]},
    "Alolan Sandslash": {"stage": 2, "requires": ["Alolan Sandshrew"]},
    "Alolan Vulpix": {"stage": 1, "evolves_to": ["Alolan Ninetales"]},
    "Alolan Ninetales": {"stage": 2, "requires": ["Alolan Vulpix"]},
    "Popplio": {"stage": 1, "evolves_to": ["Brionne"]},
    "Brionne": {"stage": 2, "requires": ["Popplio"], "evolves_to": ["Primarina"]},
    "Primarina": {"stage": 3, "requires": ["Popplio", "Brionne"]},
    "Crabrawler": {"stage": 1, "evolves_to": ["Crabominable", "Crabominable ex"]},
    "Crabominable": {"stage": 2, "requires": ["Crabrawler"]},
    "Crabominable ex": {"stage": 2, "requires": ["Crabrawler"]},
    "Dewpider": {"stage": 1, "evolves_to": ["Araquanid"]},
    "Araquanid": {"stage": 2, "requires": ["Dewpider"]},
    "Alolan Geodude": {"stage": 1, "evolves_to": ["Alolan Graveler"]},
    "Alolan Graveler": {"stage": 2, "requires": ["Alolan Geodude"], "evolves_to": ["Alolan Golem"]},
    "Alolan Golem": {"stage": 3, "requires": ["Alolan Geodude", "Alolan Graveler"]},
    "Grubbin": {"stage": 1, "evolves_to": ["Charjabug"]},
    "Charjabug": {"stage": 2, "requires": ["Grubbin"], "evolves_to": ["Vikavolt"]},
    "Vikavolt": {"stage": 3, "requires": ["Grubbin", "Charjabug"]},
    "Spoink": {"stage": 1, "evolves_to": ["Grumpig"]},
    "Grumpig": {"stage": 2, "requires": ["Spoink"]},
    "Shuppet": {"stage": 1, "evolves_to": ["Banette"]},
    "Banette": {"stage": 2, "requires": ["Shuppet"]},
    "Cutiefly": {"stage": 1, "evolves_to": ["Ribombee"]},
    "Ribombee": {"stage": 2, "requires": ["Cutiefly"]},
    "Sandygast": {"stage": 1, "evolves_to": ["Palossand"]},
    "Palossand": {"stage": 2, "requires": ["Sandygast"]},
    "Cosmog": {"stage": 1, "evolves_to": ["Cosmoem"]},
    "Cosmoem": {"stage": 2, "requires": ["Cosmog"], "evolves_to": ["Lunala", "Lunala ex", "Solgaleo", "Solgaleo ex"]},
    "Lunala": {"stage": 3, "requires": ["Cosmog", "Cosmoem"]},
    "Lunala ex": {"stage": 3, "requires": ["Cosmog", "Cosmoem"]},
    "Solgaleo": {"stage": 3, "requires": ["Cosmog", "Cosmoem"]},
    "Solgaleo ex": {"stage": 3, "requires": ["Cosmog", "Cosmoem"]},
    "Makuhita": {"stage": 1, "evolves_to": ["Hariyama"]},
    "Hariyama": {"stage": 2, "requires": ["Makuhita"]},
    "Timburr": {"stage": 1, "evolves_to": ["Gurdurr"]},
    "Gurdurr": {"stage": 2, "requires": ["Timburr"], "evolves_to": ["Conkeldurr"]},
    "Conkeldurr": {"stage": 3, "requires": ["Timburr", "Gurdurr"]},
    "Rockruff": {"stage": 1, "evolves_to": ["Lycanroc"]},
    "Lycanroc": {"stage": 2, "requires": ["Rockruff"]},
    "Mudbray": {"stage": 1, "evolves_to": ["Mudsdale"]},
    "Mudsdale": {"stage": 2, "requires": ["Mudbray"]},
    "Alolan Rattata": {"stage": 1, "evolves_to": ["Alolan Raticate"]},
    "Alolan Raticate": {"stage": 2, "requires": ["Alolan Rattata"]},
    "Alolan Meowth": {"stage": 1, "evolves_to": ["Alolan Persian"]},
    "Alolan Persian": {"stage": 2, "requires": ["Alolan Meowth"]},
    "Alolan Grimer": {"stage": 1, "evolves_to": ["Alolan Muk", "Alolan Muk ex"]},
    "Alolan Muk": {"stage": 2, "requires": ["Alolan Grimer"]},
    "Alolan Muk ex": {"stage": 2, "requires": ["Alolan Grimer"]},
    "Trubbish": {"stage": 1, "evolves_to": ["Garbodor"]},
    "Garbodor": {"stage": 2, "requires": ["Trubbish"]},
    "Mareanie": {"stage": 1, "evolves_to": ["Toxapex"]},
    "Toxapex": {"stage": 2, "requires": ["Mareanie"]},
    "Alolan Diglett": {"stage": 1, "evolves_to": ["Alolan Dugtrio"]},
    "Alolan Dugtrio": {"stage": 2, "requires": ["Alolan Diglett"]},
    "Drilbur": {"stage": 1, "evolves_to": ["Excadrill"]},
    "Excadrill": {"stage": 2, "requires": ["Drilbur"]},
    "Karrablast": {"stage": 1, "evolves_to": ["Escavalier"]},
    "Escavalier": {"stage": 2, "requires": ["Karrablast"]},
    "Escavalier": {"stage": 2, "requires": ["Excadrill"]},
    "Jangmo-o": {"stage": 1, "evolves_to": ["Hakamo-o"]},
    "Hakamo-o": {"stage": 2, "requires": ["Jangmo-o"], "evolves_to": ["Kommo-o"]},
    "Kommo-o": {"stage": 3, "requires": ["Jangmo-o", "Hakamo-o"]},
    "Skitty": {"stage": 1, "evolves_to": ["Delcatty"]},
    "Delcatty": {"stage": 2, "requires": ["Skitty"]},
    "Pikipek": {"stage": 1, "evolves_to": ["Trumbeak"]},
    "Trumbeak": {"stage": 2, "requires": ["Pikipek"], "evolves_to": ["Toucannon"]},
    "Toucannon": {"stage": 3, "requires": ["Pikipek", "Trumbeak"]},
    "Yungoos": {"stage": 1, "evolves_to": ["Gumshoos"]},
    "Gumshoos": {"stage": 2, "requires": ["Yungoos"]},
    "Stufful": {"stage": 1, "evolves_to": ["Bewear"]},
    "Bewear": {"stage": 2, "requires": ["Stufful"]},
    #A3a
    "Carvanha": {"stage": 1, "evolves_to": ["Sharpedo"]},
    "Sharpedo": {"stage": 2, "requires": ["Carvanha"]},
    "Baltoy": {"stage": 1, "evolves_to": ["Claydol"]},
    "Claydol": {"stage": 2, "requires": ["Baltoy"]},
    "Rockruff": {"stage": 1, "evolves_to": ["Lycanroc", "Lycanroc ex"]},
    "Lycanroc": {"stage": 2, "requires": ["Rockruff"]},
    "Lycanroc ex": {"stage": 2, "requires": ["Rockruff"]},
    "Sandile": {"stage": 1, "evolves_to": ["Krokorok"]},
    "Krokorok": {"stage": 2, "requires": ["Sandile"], "evolves_to": ["Krookodile"]},
    "Krookodile": {"stage": 3, "requires": ["Sandile", "Krokorok"]},
    "Poipole": {"stage": 1, "evolves_to": ["Naganadel"]},
    "Naganadel": {"stage": 2, "requires": ["Poipole"]},
    "Aron": {"stage": 1, "evolves_to": ["Lairon"]},
    "Lairon": {"stage": 2, "requires": ["Aron"], "evolves_to": ["Aggron"]},
    "Aggron": {"stage": 3, "requires": ["Aron", "Lairon"]},
    "Ferroseed": {"stage": 1, "evolves_to": ["Ferrothorn"]},
    "Ferrothorn": {"stage": 2, "requires": ["Ferroseed"]},
    "Lillipup": {"stage": 1, "evolves_to": ["Herdier"]},
    "Herdier": {"stage": 2, "requires": ["Lillipup"], "evolves_to": ["Stoutland"]},
    "Stoutland": {"stage": 3, "requires": ["Lillipup", "Herdier"]},
    "Type: Null": {"stage": 1, "evolves_to": ["Silvally"]},
    "Silvally": {"stage": 2, "requires": ["Type: Null"]},
    #A3b
    "Applin": {"stage": 1, "evolves_to": ["Appletun"]},
    "Appletun": {"stage": 2, "requires": ["Applin"]},
    "Vanillite": {"stage": 1, "evolves_to": ["Vanillish"]},
    "Vanillish": {"stage": 2, "requires": ["Vanillite"], "evolves_to": ["Vanilluxe"]},
    "Vanilluxe": {"stage": 3, "requires": ["Vanillite", "Vanillish"]},
    "Joltik": {"stage": 1, "evolves_to": ["Galvantula"]},
    "Galvantula": {"stage": 2, "requires": ["Joltik"]},
    "Milcery": {"stage": 1, "evolves_to": ["Alcremie"]},
    "Alcremie": {"stage": 2, "requires": ["Milcery"]},
    "Skwovet": {"stage": 1, "evolves_to": ["Greedent"]},
    "Greedent": {"stage": 2, "requires": ["Skwovet"]}
}

# Seznam karet trenérů (PA 001–008 a další, podle názvu)
trainer_cards = ["Potion", "X Speed", "Hand Scope", "Pokedex", "Poke Ball", "Red Card", 
                 "Professor's Research", "Pokémon Flute", "Eevee Bag"]

# Extrakce dat: Procházení všech tabulek na stránce
for table in soup.find_all("table"):
    # Získání všech řádků v tabulce
    rows = table.find_all("tr")
    i = 0
    while i < len(rows):
        try:
            # Extrakce názvu karty (první řádek)
            name = rows[i].find("p").get_text(strip=True) if rows[i].find("p") else ""
            # Extrakce kódu karty (druhý řádek)
            code = rows[i+1].find("p").get_text(strip=True) if i+1 < len(rows) and rows[i+1].find("p") else ""

            # Kontrola, zda nejsou název nebo kód prázdné
            if not name or not code:
                skipped_rows.append((i, f"Chybějící pole: název={name}, kód={code}"))
                i += 1
                continue

            # Validace formátu kódu (např. A1 001, A1a 001, PA 001)
            if not re.match(r"[A-Z]+\d*[a-z]?\s*\d+", code.replace(" ", "")):
                skipped_rows.append((i, f"Neplatný kód: {code}"))
                i += 1
                continue

            # Přidání karty do seznamu s requires a evolves_to
            all_cards.append({"code": code, "name": name, "requires": "", "evolves_to": ""})

            # Posun na další kartu: 3 řádky, pokud třetí řádek obsahuje <p>, jinak 4
            i += 3 if i+3 < len(rows) and rows[i+2].find("p") else 4

        except Exception:
            # Zachycení chyb při parsování
            skipped_rows.append((i, "Chyba při parsování řádku"))
            i += 1

# Transformace: Přidání závislostí pro Pokémony
for card in all_cards:
    name = card["name"]
    # Karty trenérů nemají závislosti
    if name in trainer_cards:
        card["requires"] = "None"
        card["evolves_to"] = "None"
    # Pokémoni: Kontrola evolučních řetězců
    elif name in evolution_chains:
        chain = evolution_chains[name]
        # Přidání requires (karty potřebné pro zahrání)
        if chain.get("stage", 1) == 1:
            card["requires"] = "None"  # Základní Pokémoni nemají závislosti
        else:
            required_names = chain.get("requires", [])
            req_codes = [c["code"] for c in all_cards if c["name"] in required_names]
            card["requires"] = ";".join(req_codes) if req_codes else "None"
        # Přidání evolves_to (karty, do kterých lze vyvinout)
        evolves_to_names = chain.get("evolves_to", [])
        evolves_codes = [c["code"] for c in all_cards if c["name"] in evolves_to_names]
        card["evolves_to"] = ";".join(evolves_codes) if evolves_codes else "None"
    else:
        # Neznámé Pokémony nemají závislosti
        card["requires"] = "None"
        card["evolves_to"] = "None"

# Uložení dat do CSV
with open("cards.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=["code", "name", "requires", "evolves_to"])
    writer.writeheader()  # Zápis hlavičky CSV
    writer.writerows(all_cards)  # Zápis všech karet

# Výpis výsledku a ladících informací
print(f"Exportováno {len(all_cards)} karet do cards.csv")
if skipped_rows:
    print("\nPřeskočené řádky:")
    for row_idx, reason in skipped_rows:
        print(f"Řádek {row_idx}: {reason}")